runtime: nodejs12
handlers:
  # Serve all static files with url ending with a file extension  
  - url: /
    static_files: build/index.html
    upload: build/index.html
    
  - url: /
    static_dir: build
